In [1]:
import pandas as pd

df=pd.read_csv("QVI_purchase_behaviour.csv")
df.head()

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

In [2]:
df.isnull().sum()

LYLTY_CARD_NBR      0
LIFESTAGE           0
PREMIUM_CUSTOMER    0
dtype: int64

In [3]:
df["LIFESTAGE"].value_counts()

LIFESTAGE
RETIREES                  14805
OLDER SINGLES/COUPLES     14609
YOUNG SINGLES/COUPLES     14441
OLDER FAMILIES             9780
YOUNG FAMILIES             9178
MIDAGE SINGLES/COUPLES     7275
NEW FAMILIES               2549
Name: count, dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df["LYLTY_CARD_NBR"].nunique(), len(df)

(72637, 72637)

In [6]:
df["PREMIUM_CUSTOMER"].value_counts()

PREMIUM_CUSTOMER
Mainstream    29245
Budget        24470
Premium       18922
Name: count, dtype: int64

In [7]:
trans_df=pd.read_csv("clean_transaction.csv")
trans_df.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,Pack_Size,Brand
0,2018-10-17,1,1000,1,5,NATURAL CHIP COMPNY SEASALT175G,2,6.0,175.0,NATURAL CHIP
1,2019-05-14,1,1307,348,66,CCS NACHO CHEESE 175G,3,6.3,175.0,CCS
2,2019-05-20,1,1343,383,61,SMITHS CRINKLE CUT CHIPS CHICKEN 170G,2,2.9,170.0,SMITHS
3,2018-08-17,2,2373,974,69,SMITHS CHIP THINLY S/CREAM&ONION 175G,5,15.0,175.0,SMITHS
4,2018-08-18,2,2426,1038,108,KETTLE TORTILLA CHPSHNY&JLPNO CHILI 150G,3,13.8,150.0,KETTLE

In [8]:
merged_df=pd.merge(trans_df,df,on="LYLTY_CARD_NBR",how="inner")

In [9]:
merged_df.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,Pack_Size,Brand,LIFESTAGE,PREMIUM_CUSTOMER
0,2018-10-17,1,1000,1,5,NATURAL CHIP COMPNY SEASALT175G,2,6.0,175.0,NATURAL CHIP,YOUNG SINGLES/COUPLES,Premium
1,2019-05-14,1,1307,348,66,CCS NACHO CHEESE 175G,3,6.3,175.0,CCS,MIDAGE SINGLES/COUPLES,Budget
2,2019-05-20,1,1343,383,61,SMITHS CRINKLE CUT CHIPS CHICKEN 170G,2,2.9,170.0,SMITHS,MIDAGE SINGLES/COUPLES,Budget
3,2018-08-17,2,2373,974,69,SMITHS CHIP THINLY S/CREAM&ONION 175G,5,15.0,175.0,SMITHS,MIDAGE SINGLES/COUPLES,Budget
4,2018-08-18,2,2426,1038,108,KETTLE TORTILLA CHPSHNY&JLPNO CHILI 150G,3,13.8,150.0,KETTLE,MIDAGE SINGLES/COUPLES,Budget

In [10]:
merged_df.shape

(264835, 12)

In [11]:
merged_df.duplicated().sum()

np.int64(0)

In [12]:
merged_df.isnull().sum()

DATE                0
STORE_NBR           0
LYLTY_CARD_NBR      0
TXN_ID              0
PROD_NBR            0
PROD_NAME           0
PROD_QTY            0
TOT_SALES           0
Pack_Size           0
Brand               0
LIFESTAGE           0
PREMIUM_CUSTOMER    0
dtype: int64

In [13]:
merged_df.to_csv("Final_Transaction_Purchase.csv",index=False)